.

diff --git a/.github/workflows/ci_pattern.yml b/.github/workflows/ci_pattern.yml
--- a/.github/workflows/ci_pattern.yml
+++ b/.github/workflows/ci_pattern.yml
@@ -41,51 +41,18 @@ jobs:
       - name: Download .text files
         run: |
           BASE_URL="https://raw.githubusercontent.com/DaniGP17/fivem/feat/ci-pattern-check/builds"
-
-          BUILDS_FIVEM=(1604 2060 2189 2372 2545 2612 2699 2802 2944 3095 3258 3323 3407 3570)
-          BUILDS_REDM=(1491)
+          ARCHIVE_NAME="GameBuildsText.7z"
 
           mkdir -p Release/Builds
           cd Release/Builds
 
-          download_builds() {
-            local prefix="$1"
-            shift
-            local builds=("$@")
+          echo "Downloading $ARCHIVE_NAME..."
+          curl -sSfL --retry 3 -o "$ARCHIVE_NAME" "$BASE_URL/$ARCHIVE_NAME" || { echo "Error downloading $ARCHIVE_NAME"; exit 1; }
 
-            export BASE_URL
-            export prefix
+          echo "Extracting $ARCHIVE_NAME..."
+          7z x "$ARCHIVE_NAME" -y > /dev/null || { echo "Failed to extract archive"; exit 1; }
 
-            printf "%s\n" "${builds[@]}" | xargs -n1 -P"$(nproc)" bash -c '
-              build="$1"
-              FILE="${prefix}-${build}.text"
-              echo "Downloading $FILE..."
-              curl -sSfL --retry 3 -o "$FILE" "$BASE_URL/$FILE" || { echo "Error downloading $FILE"; exit 1; }
-            ' _
-          }
-
-          case "${{ inputs.game }}" in
-            fivem)
-              download_builds "GTA5" "${BUILDS_FIVEM[@]}"
-              ;;
-            redm)
-              download_builds "RDR2" "${BUILDS_REDM[@]}"
-              ;;
-            both)
-              echo "Downloading RedM builds..."
-              download_builds "RDR2" "${BUILDS_REDM[@]}"
-              echo "Downloading FiveM builds..."
-              download_builds "GTA5" "${BUILDS_FIVEM[@]}"
-              ;;
-            none)
-              echo "No game selected, skipping download."
-              exit 0
-              ;;
-            *)
-              echo "Unknown game value: ${{ inputs.game }}"
-              exit 1
-              ;;
-          esac
+          echo "Done."
 
       - name: Run PatternV
         id: run_patternv
