a

diff --git a/.github/workflows/ci_pattern.yml b/.github/workflows/ci_pattern.yml
--- a/.github/workflows/ci_pattern.yml
+++ b/.github/workflows/ci_pattern.yml
@@ -48,19 +48,40 @@ jobs:
           cmake ..
           make -j$(nproc)
 
-      - name: Download .text files
+            - name: Download .text files
         run: |
           BASE_URL="https://raw.githubusercontent.com/DaniGP17/fivem/feat/ci-pattern-check/builds"
-          BUILDS=(1604 2060 2189 2372 2545 2612 2699 2802 2944 3095 3258 3323 3407 3570)
+
+          # Decidir builds según el juego
+          case "${{ inputs.game }}" in
+            fivem)
+              BUILDS=(1491)
+              ;;
+            redm)
+              BUILDS=(1604 2060 2189 2372 2545 2612 2699 2802 2944 3095 3258 3323 3407 3570)
+              ;;
+            both)
+              BUILDS=(1491 1604 2060 2189 2372 2545 2612 2699 2802 2944 3095 3258 3323 3407 3570)
+              ;;
+            none)
+              echo "No game selected, skipping download."
+              exit 0
+              ;;
+            *)
+              echo "Unknown game value: ${{ inputs.game }}"
+              exit 1
+              ;;
+          esac
           
           mkdir -p Release/Builds
           cd Release/Builds
           
           for build in "${BUILDS[@]}"; do
             FILE="GTA5-${build}.text"
-            echo "Descargando $FILE..."
-            curl -L -o "$FILE" "$BASE_URL/$FILE"
+            echo "Downloading $FILE..."
+            curl -f -L -o "$FILE" "$BASE_URL/$FILE" || { echo "Error downloading $FILE"; exit 1; }
           done
+
 
       - name: Run PatternV
         run: |
